config/routes.rb
OklahomaatheistsCom::Application.routes.draw do
  root "home#index"

  resource :board
  resource :contact

  get "/redirect" => "domains#show"
end

app/views/layouts/_footer_blog_posts.html.erb
<h4>Recent Blog <span>Posts</span><span class="h-line"></span></h4>

<ul id="popular_post">
  <% @blog_posts.first(6).each do |post| %>
    <li><p><%= link_to truncate(post.title, length: 50), post.url %></p></li>
  <% end %>
</ul>

<%= link_to %Q{+ View All <span class="h-line"></span>}.html_safe, AOK::APIs.blogger.blog_url, class: "v-a" %>

app/views/layouts/_footer_contact_form.html.erb
<h4>GET IN <span>Touch</span><span class="h-line"></span></h4>

<p>You can use the form below or contact us by mail:  P.O. Box 12412, Oklahoma City, OK 73157.</p>

<%= form_tag(contact_path, id: "contact_form") do %>
  <%= text_field_tag :name,    "", placeholder: "Name",     required: "required" %>
  <%= text_field_tag :email,   "", placeholder: "Email",    required: "required" %>
  <div class="special-alignment">
    <%= text_field_tag :subject, "", placeholder: "Subject" %>
  </div>
  <%= text_area_tag  :message, "", placeholder: "Comments", required: "required", rows: 5, cols: 20 %>
  <%= submit_tag "Send Message" %>
<% end %>

app/views/layouts/_footer_contact_info.html.erb
<%= mail_to AOK::EMAIL, icon(:envelope_alt) %> <span><%= mail_to AOK::EMAIL %></span>

app/views/layouts/_footer_friends.html.erb
<h4>Friends of the <span>AOK</span><span class="h-line"></span></h4>

<ul id="popular_post">
  <% friends.each do |friend| %>
    <li><p><%= link_to friend.name.gsub("\n", "<br>").html_safe, friend.url %></p></li>
  <% end %>
</ul>

<a class="v-a"><span class="h-line"></span></a>

app/views/layouts/_footer_join_banner.html.erb
<h2>Join our online community at <%= link_to "Facebook.com", AOK::SOCIAL_MEDIA_ACCOUNTS["Facebook"].url %></h2>
<h3>Or join us for in-person events listed at <%= link_to "Meetup.com", nav_links.find { |link| link.title == "Events" }.url %></h3>

app/views/layouts/_footer_nav_links.html.erb
<ul class="footer_nav">
  <% nav_links.each do |link| %>
    <% next unless link.footer? %>
    <li><%= link_to link.title, link.url %></li>
  <% end %>
</ul>

app/views/layouts/_footer_quotes.html.erb
<ul id="latest_tweets">
  <% quote = quotes.sample %>
  <li>&ldquo;<%= quote.comment %>&rdquo;&mdash;<%= quote.by %></li>
</ul>

app/views/layouts/_footer_social_media.html.erb
<div id="socialicons">
  <% AOK::SOCIAL_MEDIA_ACCOUNTS.each_value do |account| %>
    <%= link_to content_tag(:span, " "), account.url, data: {placement: "top"}, rel: "tooltip", title: account.call_to_action, id: "social_#{account.service.downcase.sub('+', '_plus')}", class: "social_active" %>
  <% end %>
</div>

app/views/layouts/_footer_tweets.html.erb
<h4>Latest Twitter <span> Updates </span> <span class="h-line"></span> </h4>

<ul id="tweets_crunchpress">
  <% @tweets.first(2).each do |tweet| %>
    <li>
      <%= tweet.linked_text.html_safe %>
      <span>&mdash;<%= link_to "#{time_ago_in_words(tweet.time)} ago", tweet.url %></span>
    </li>
  <% end %>
</ul>

<%= link_to "+ View All #{content_tag(:span, '', class: 'h-line')}".html_safe, AOK::SOCIAL_MEDIA_ACCOUNTS["Twitter"].url, class: "v-a" %>

app/views/layouts/_header_contact_info.html.erb
<ul class="details">
  <li><%= mail_to AOK::EMAIL, icon(:envelope_alt) %> <%= mail_to AOK::EMAIL %></li>
</ul>

app/views/layouts/_header_nav_links.html.erb
<ul class="nav">
  <% nav_links.each do |link| %>
    <% if link.nested_links.empty? %>
      <li<%= raw ' class="active"' if active_nav_link == link %>><%= link_to link.title, link.url %></li>
    <% else %>
      <li class="dropdown<%= raw ' active' if active_nav_link == link %>">
        <ul class="dropdown-menu">
          <% link.nested_links.each do |nested_link| %>
            <li<%= raw ' class="active"' if active_nav_link == nested_link %>><%= link_to nested_link.title, nested_link.url %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_header_social_media.html.erb
<ul class="social">
  <% AOK::SOCIAL_MEDIA_ACCOUNTS.values.reverse_each do |account| %>
    <li><%= link_to account.service, account.url, class: account.css_class %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Oklahoma Atheists</title>

    <link rel="icon" type="image/x-icon" href="<%= image_path("favicon.ico") %>">

    <!--[if lt IE 9]>
      <%= javascript_include_tag :html5shiv %>
    <![endif]-->
    <!--[if lt IE 9]>
      <%= javascript_include_tag :mq %>
    <![endif]-->

    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag :application %>
    <!--[if lte IE 9]><%= stylesheet_link_tag :customIE %><![endif]-->
    <noscript>
      <%= stylesheet_link_tag :nj %>
    </noscript>

    <%= javascript_include_tag :application %>
    <!--[if IE 8]>
      <%= javascript_include_tag :ie8_fix_maxwidth %>
    <![endif]-->

    <%= yield(:head) %>
  </head>
  <body>
    <div class="wrapper">
      <header>
        <section class="top_bar">
          <section class="container-fluid container">
            <section class="row-fluid">
              <article class="span6">
                <%= render "layouts/header_contact_info" %>
              </article>

              <article class="span4 offset2">
                <%= render "layouts/header_social_media" %>
              </article>
            </section>
          </section>
        </section>

        <section class="logo_container">
          <section class="container-fluid container">
            <section class="row-fluid">
              <section class="span12">
                <h1 id="logo">
                  <%= link_to image_tag("banner.png"), root_path %>
                </h1>
              </section>
            </section>
          </section>
        </section>

        <nav id="nav">
          <section class="container-fluid container">
            <section class="row-fluid">
              <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                  <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                  <div class="nav-collapse collapse">
                    <%= render "layouts/header_nav_links" %>
                  </div>
                </div>
              </div>
            </section>
          </section>
        </nav>
      </header>

      <%= yield %>

      <footer id="footer" class="mtp">
        <section class="footer_1">
          <section class="container-fluid container">
            <section class="row-fluid">
              <section id="banner" class="span12 first">
                <div class="inner">
                  <div class="span12">
                    <%= render "layouts/footer_join_banner" %>
                  </div>
                </div>
              </section>

              <section class="span12 first" id="footer_main">
                <section class="span3 first widget">
                  <%= render "layouts/footer_contact_form" %>
                </section>

                <section class="span3 widget popular_post">
                  <%= render "layouts/footer_blog_posts" %>
                </section>

                <section class="widget span3">
                  <%= render "layouts/footer_tweets" %>
                </section>

                <section class="span3 widget">
                  <%= render "layouts/footer_friends" %>
                </section>
              </section>
            </section>
          </section>
        </section>

        <section class="footer_2">
          <section class="container-fluid container">
            <section class="row-fluid">
              <figure class="span6" id="footer_left"><%= render "layouts/footer_contact_info" %></figure>

              <figure class="span6" id="footer_right">
                <%= render "layouts/footer_social_media" %>
              </figure>
            </section>
          </section>
        </section>

        <section class="footer_3">
          <section class="container-fluid container">
            <section class="row-fluid">
              <figure class="span6" id="footer_left">
                <%= render "layouts/footer_nav_links" %>

                <p>Copyright © <%= Time.now.year %> &ndash; Oklahoma Atheists</p>
              </figure>

              <figure class="span6" id="footer_right">
                <div id="tweets" class="latest_tweets">
                  <%= render "layouts/footer_quotes" %>
                </div>
              </figure>
            </section>
          </section>
        </section>
      </footer>
    </div>
  </body>
</html>